#!/usr/bin/env bash

set -e

ACTION=$1

function traduire {
	if [[ "$2" == "--aide" ]]; then
	  docker "$1" --help | sed "s/docker $1/marcel $ACTION/"
	else
	  docker "$1" "${*:2}"
	fi
}

case "$ACTION" in
attache)
	traduire "attach" "${*:2}"
  ;;

construis)
  traduire "build" "${*:2}"
  ;;

engage)
  traduire "commit" "${*:2}"
  ;;

copie)
  traduire "cp" "${*:2}"
  ;;

crée)
  traduire "create" "${*:2}"
  ;;

changements)
  traduire "diff" "${*:2}"
  ;;

événements|évènements)
  traduire "events" "${*:2}"
  ;;

réalise)
	traduire "exec" "${*:2}"
	;;

exporte)
	traduire "export" "${*:2}"
	;;

historique)
	traduire "history" "${*:2}"
	;;

images)
	traduire "images" "${*:2}"
	;;

importe)
	traduire "import" "${*:2}"
	;;

info)
	traduire "info" "${*:2}"
	;;

inspecte)
	traduire "inspect" "${*:2}"
	;;

tue)
	traduire "kill" "${*:2}"
	;;

charge)
	traduire "load" "${*:2}"
	;;

connecte)
	traduire "login" "${*:2}"
	;;

déconnecte)
	traduire "logout" "${*:2}"
	;;

journal)
	traduire "logs" "${*:2}"
	;;

réseau)
	traduire "network" "${*:2}"
	;;

bloque)
	traduire "pause" "${*:2}"
	;;

port)
	traduire "port" "${*:2}"
	;;

liste)
	traduire "ps" "${*:2}"
	;;

récupère)
	traduire "pull" "${*:2}"
	;;

publie)
	traduire "push" "${*:2}"
	;;

renomme)
	traduire "rename" "${*:2}"
	;;

redémarre)
	traduire "restart" "${*:2}"
	;;

suppr)
	traduire "rm" "${*:2}"
	;;

sim)
	traduire "rmi" "${*:2}"
	;;

lance)
	traduire "run" "${*:2}"
	;;

sauvegarde)
	traduire "save" "${*:2}"
	;;

recherche)
	traduire "search" "${*:2}"
	;;

démarre)
	traduire "start" "${*:2}"
	;;

stats)
	traduire "stats" "${*:2}"
	;;

arrête)
	traduire "stop" "${*:2}"
	;;

labellise)
	traduire "tag" "${*:2}"
	;;

premiers)
	traduire "top" "${*:2}"
	;;

débloque)
	traduire "unpause" "${*:2}"
	;;

version)
	traduire "version" "${*:2}"
	;;

tome)
	traduire "volume" "${*:2}"
	;;

attend)
	traduire wait "${*:2}"
	;;

*)
	docker --help | sed "s/docker/marcel/" | sed "s/--help/--aide/"
esac
